# Generated by Django 4.1.dev20210929182329 on 2021-10-09 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Finch',
        ),
    ]
