# Generated by Django 4.1.dev20210929182329 on 2021-10-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='img',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
