# Generated by Django 4.1.dev20210929182329 on 2021-10-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_finch_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='adult_size',
            field=models.TextField(),
        ),
    ]
