# Generated by Django 4.1.dev20210929182329 on 2021-10-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_finch_adult_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='adult_size',
            field=models.TextField(max_length=10),
        ),
    ]
