# Generated by Django 4.1.dev20210929182329 on 2021-10-12 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_finch_adult_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('aggression', models.CharField(max_length=250)),
                ('egg_laying', models.CharField(max_length=250)),
                ('finch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior', to='main_app.finch')),
            ],
        ),
    ]
