# Generated by Django 4.1.dev20210929182329 on 2021-10-12 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_behavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='finch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='main_app.finch'),
        ),
    ]
