# Generated by Django 4.1.dev20210929182329 on 2021-10-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_behavior_aggression_alter_behavior_egg_laying'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='aggression',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='egg_laying',
            field=models.TextField(max_length=1000),
        ),
    ]
