# Generated by Django 3.2.7 on 2021-10-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_behavior_aggression_alter_behavior_egg_laying'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinchDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=100)),
                ('adult_size', models.TextField(max_length=10)),
                ('lifespan', models.TextField(max_length=250)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Behavior',
        ),
    ]
